### ISSUE TITLE
Write empty functions and docstrings

### ISSUE THREAD

**Issue by sreejithmunthikodu** [UBC-MDS/KmeansR#2]
1. **Function to fit** - Implement k-means algorithm and get the centroids
2. **Function to predict** - given the centroids of the clusters, assign new data to the respective clusters. 
3. Function to select the best k using **silhotte method** - given a list of k and data, plot the silhouette score vs k
4. Function to select the best k using **elbow method** - given list of k and data, plot the inertia vs k
5. **Function to summarize the clusters** - Given a fitted k-means function, return the summary of clusters as a data frame- how many clusters, number of samples in each cluster, cluster quality, etc.

**Comment by sreejithmunthikodu** [comment]
Guys, let's discuss the possible functions, input arguments, and output here. Once we finalize the number and type of functions, we can open separate issues for each function and take ownership.

Also, we should discuss if we are using classes or independent functions.

**Comment by RobBlumberg** [comment]
We can link specific issues for each function to the discussions we had in the python repo so that we don't have to re-discuss inputs/ouputs. Also documentation should follow roxygen style:

#' Description
#'
#' @param <name> description 
#' @param <name> description 
#' @param etc.
#'
#' @return <type> description
#'
#' @examples
#' function()

This is the right format for roxygen right?
